// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_EventSpawnTimers","status":true,"description":"Enable psuedo-timers that can control event self-switches, switches and variables.","parameters":{"X":""}}
];
